return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		local configs = require("nvim-treesitter.configs")

		configs.setup({
			ensure_installed = {
				"markdown",
				"markdown_inline",
				"bash",
				"c",
				"cmake",
				"cpp",
				"lua",
				"luadoc",
				"vim",
				"vimdoc",
				"query",
				-- "elixir",
				-- "heex",
				"javascript",
				"html",
				"css",
				"typescript",
				"tsx",
				"csv",
				"tsv",
				"dot",
				"diff",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"http",
				"java",
				"json",
				"jsdoc",
				-- "prisma",
				"python",
				"regex",
				"scss",
				-- "sql",
				-- "svelte",
				-- "toml",
				"yaml",
				"php",
				-- "phpdoc",
				-- "pioasm",
			},
			sync_install = false,
			highlight = { enable = true },
			indent = { enable = true },
		})
	end,
}
